version: "2"
services:
  postgres:
    image: 'postgres'
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    container_name: 'chat360-db'
    restart: 'always'
    env_file:
      - _database.env
    ports:
      - '5432:5432'
    networks:
      - chat360

  redis:
    image: 'bitnami/redis:latest'
    volumes:
      - redis:/var/lib/redis/data/
    container_name: 'chat360-redis'
    restart: 'always'
    env_file:
      - _database.env
    ports:
      - '6379:6379'
    networks:
      - chat360  

  chat360-backend:
    build:
      context: .
    image: chat360-backend:latest
    container_name: chat360-backend
    depends_on:
      - postgres

    volumes:
      - ./src:/app/src
      - .env:/app/.env
    ports:
      - '3836:3836'
    networks:
      - chat360
               
networks:
  chat360:
volumes:
  postgres-data:
  redis:
 
